--5.1--
CREATE TABLE ATORES(
    IDATOR INT,
    NOME_ATOR VARCHAR(1000),
    PAIS_ATOR INT,
    ATUAL_ESTADO INT,
    NASCIMENTO DATE,
    FALECIMENTO DATE
);

--5.2--
--CONSTRAINT--

--PRIMARY KEY--
ALTER TABLE ATORES ADD CONSTRAINT PK_ATORES
PRIMARY KEY(IDATOR);

ALTER TABLE ATORES MODIFY IDATOR INT AUTO_INCREMENT;

--PAIS--
ALTER TABLE ATORES ADD CONSTRAINT FK_PAIS_ATOR 
FOREIGN KEY(PAIS_ATOR) REFERENCES PAISES(IDPAIS);

--ATUAL ESTADO--
ALTER TABLE ATORES ADD CONSTRAINT FK_ATUAL_ESTADO_ATOR
FOREIGN KEY(ATUAL_ESTADO) REFERENCES ATUAL_ESTADO(IDATUAL_ESTADO);