--4.1--
CREATE TABLE ATUAL_ESTADO(
    IDATUAL_ESTADO INT,
    NOME_ATUAL_ESTADO VARCHAR(1000)
);

--4.2--
--CONSTRAINTS--

--PRIMARY KEY--
ALTER TABLE ATUAL_ESTADO ADD CONSTRAINT PK_ATUAL_ESTADO
PRIMARY KEY(IDATUAL_ESTADO);

ALTER TABLE ATUAL_ESTADO MODIFY IDATUAL_ESTADO INT AUTO_INCREMENT;