--6.1--
CREATE TABLE AUTORES(
    IDAUTOR INT,
    NOME_AUTOR VARCHAR(1000),
    PAIS_AUTOR INT,
    ATUAL_ESTADO INT,
    NASCIMENTO DATE,
    FALECIMENTO DATE
);

--6.2--
--CONSTRAINTS--

--PRIMARY KEY--
ALTER TABLE AUTORES ADD CONSTRAINT PK_AUTORES
PRIMARY KEY(IDAUTOR);

ALTER TABLE AUTORES MODIFY IDAUTOR INT AUTO_INCREMENT;

--PAIS--
ALTER TABLE AUTORES ADD CONSTRAINT FK_PAIS_AUTOR 
FOREIGN KEY(PAIS_AUTOR) REFERENCES PAISES(IDPAIS);

--ATUAL ESTADO--
ALTER TABLE AUTORES ADD CONSTRAINT FK_ATUAL_ESTADO_AUTOR
FOREIGN KEY(ATUAL_ESTADO) REFERENCES ATUAL_ESTADO(IDATUAL_ESTADO);