--7.1--
CREATE TABLE DIRETORES(
    IDDIRETOR INT,
    NOME_DIRETOR VARCHAR(1000),
    PAIS_DIRETOR INT,
    ATUAL_ESTADO INT,
    NASCIMENTO DATE,
    FALECIMENTO DATE
);

--7.2--
--CONSTRAINT--

--PRIMARY KEY--
ALTER TABLE DIRETORES ADD CONSTRAINT PK_DIRETORES
PRIMARY KEY(IDDIRETOR);

ALTER TABLE DIRETORES MODIFY IDDIRETOR INT AUTO_INCREMENT;

--PAIS--
ALTER TABLE DIRETORES ADD CONSTRAINT FK_PAIS_DIRETOR 
FOREIGN KEY(PAIS_DIRETOR) REFERENCES PAISES(IDPAIS);

--ATUAL ESTADO--
ALTER TABLE DIRETORES ADD CONSTRAINT FK_ATUAL_ESTADO_DIRETOR
FOREIGN KEY(ATUAL_ESTADO) REFERENCES ATUAL_ESTADO(IDATUAL_ESTADO);