--8.1--
CREATE TABLE EDITORAS(
    IDEDITORA INT,
    NOME_EDITORA VARCHAR(1000),
    PAIS_EDITORA INT,
    FUNDADA DATE
);

--8.2--
--CONSTRAINTS--

--PRIMARY KEY--
ALTER TABLE EDITORAS ADD CONSTRAINT PK_EDITORAS
PRIMARY KEY(IDEDITORA);

ALTER TABLE EDITORAS MODIFY IDEDITORA INT AUTO_INCREMENT;

--PAIS--
ALTER TABLE EDITORAS ADD CONSTRAINT FK_PAIS_EDITORA
FOREIGN KEY(PAIS_EDITORA) REFERENCES PAISES(IDPAIS);