--9.1--
CREATE TABLE ESTUDIOS(
    IDESTUDIO INT,
    NOME_ESTUDIO VARCHAR(1000),
    PAIS_ESTUDIO INT,
    FUNDADA DATE
);

--9.2--
--CONSTRAINTS--

--PRIMARY KEY
ALTER TABLE ESTUDIOS ADD CONSTRAINT PK_ESTUDIO
PRIMARY KEY(IDESTUDIO);

ALTER TABLE ESTUDIOS MODIFY IDESTUDIO INT AUTO_INCREMENT;

--PAIS--
ALTER TABLE ESTUDIOS ADD CONSTRAINT FK_PAIS_ESTUDIO
FOREIGN KEY(PAIS_ESTUDIO) REFERENCES PAISES(IDPAIS);