--13.1--
CREATE TABLE FILMES (
    IDFILME INT,
    NOME_FILME VARCHAR(1000) NOT NULL,
    NOME_ORIGINAL_FILME VARCHAR(1000) NOT NULL,
    PAIS_FILME INT,
    DATA_LANCAMENTO DATE,
    PRODUTORA1 INT,
    PRODUTORA2 INT,
    PRODUTORA3 INT,
    DIRETOR1 INT,
    DIRETOR2 INT,
    DIRETOR3 INT,
    DIRETOR4 INT,
    ATOR1 INT,
    ATOR2 INT,
    ATOR3 INT,
    ATOR4 INT,
    ATOR5 INT,
    ATOR6 INT,
    ATOR7 INT,
    ATOR8 INT,
    ATOR9 INT,
    ATOR10 INT,
    GENERO_FILME1 INT,
    GENERO_FILME2 INT,
    GENERO_FILME3 INT,
    GENERO_FILME4 INT,
    GENERO_FILME5 INT,
    SINOPSE_FILME TEXT,
    CLASSIFICACAO_ETARIA INT,
    DURACAO_FILME TIME,
    EU_VI ENUM("Sim",'Não'),
    MINHA_NOTA NUMERIC(4,2),
    MEU_COMENTARIO TEXT
);

--13.2--
--CONSTRAINT--

--PRIMARY KEY--
ALTER TABLE FILMES ADD CONSTRAINT PK_FILMES
PRIMARY KEY(IDFILME);

ALTER TABLE FILMES MODIFY IDFILME INT AUTO_INCREMENT;

--PAIS--
ALTER TABLE FILMES ADD CONSTRAINT FK_PAIS_FILME
FOREIGN KEY(PAIS_FILME) REFERENCES PAISES(IDPAIS);

--PRODUTORAS--
ALTER TABLE FILMES ADD CONSTRAINT FK_PRODUTORA1
FOREIGN KEY(PRODUTORA1) REFERENCES PRODUTORAS(IDPRODUTORA);

ALTER TABLE FILMES ADD CONSTRAINT FK_PRODUTORA2
FOREIGN KEY(PRODUTORA2) REFERENCES PRODUTORAS(IDPRODUTORA);

ALTER TABLE FILMES ADD CONSTRAINT FK_PRODUTORA3
FOREIGN KEY(PRODUTORA3) REFERENCES PRODUTORAS(IDPRODUTORA);

--DIRETORES--
ALTER TABLE FILMES ADD CONSTRAINT FK_DIRETOR1_FILME
FOREIGN KEY(DIRETOR1) REFERENCES DIRETORES(IDDIRETOR);

ALTER TABLE FILMES ADD CONSTRAINT FK_DIRETOR2_FILME
FOREIGN KEY(DIRETOR2) REFERENCES DIRETORES(IDDIRETOR);

ALTER TABLE FILMES ADD CONSTRAINT FK_DIRETOR3_FILME 
FOREIGN KEY(DIRETOR3) REFERENCES DIRETORES(IDDIRETOR);

ALTER TABLE FILMES ADD CONSTRAINT FK_DIRETOR4_FILME 
FOREIGN KEY(DIRETOR4) REFERENCES DIRETORES(IDDIRETOR);

--ATORES--
ALTER TABLE FILMES ADD CONSTRAINT FK_ATOR1_FILME
FOREIGN KEY(ATOR1) REFERENCES ATORES(IDATOR);

ALTER TABLE FILMES ADD CONSTRAINT FK_ATOR2_FILME
FOREIGN KEY(ATOR2) REFERENCES ATORES(IDATOR);

ALTER TABLE FILMES ADD CONSTRAINT FK_ATOR3_FILME
FOREIGN KEY(ATOR3) REFERENCES ATORES(IDATOR);

ALTER TABLE FILMES ADD CONSTRAINT FK_ATOR4_FILME
FOREIGN KEY(ATOR4) REFERENCES ATORES(IDATOR);

ALTER TABLE FILMES ADD CONSTRAINT FK_ATOR5_FILME
FOREIGN KEY(ATOR5) REFERENCES ATORES(IDATOR);

ALTER TABLE FILMES ADD CONSTRAINT FK_ATOR6_FILME
FOREIGN KEY(ATOR6) REFERENCES ATORES(IDATOR);

ALTER TABLE FILMES ADD CONSTRAINT FK_ATOR7_FILME
FOREIGN KEY(ATOR7) REFERENCES ATORES(IDATOR);

ALTER TABLE FILMES ADD CONSTRAINT FK_ATOR8_FILME
FOREIGN KEY(ATOR8) REFERENCES ATORES(IDATOR);

ALTER TABLE FILMES ADD CONSTRAINT FK_ATOR9_FILME
FOREIGN KEY(ATOR9) REFERENCES ATORES(IDATOR);

ALTER TABLE FILMES ADD CONSTRAINT FK_ATOR10_FILME
FOREIGN KEY(ATOR10) REFERENCES ATORES(IDATOR);

--GÊNEROS--
ALTER TABLE FILMES ADD CONSTRAINT FK_GENERO_FILME1
FOREIGN KEY(GENERO_FILME1) REFERENCES GENEROS(IDGENERO);

ALTER TABLE FILMES ADD CONSTRAINT FK_GENERO_FILME2
FOREIGN KEY(GENERO_FILME2) REFERENCES GENEROS(IDGENERO);

ALTER TABLE FILMES ADD CONSTRAINT FK_GENERO_FILME3
FOREIGN KEY(GENERO_FILME3) REFERENCES GENEROS(IDGENERO);

ALTER TABLE FILMES ADD CONSTRAINT FK_GENERO_FILME4
FOREIGN KEY(GENERO_FILME4) REFERENCES GENEROS(IDGENERO);

ALTER TABLE FILMES ADD CONSTRAINT FK_GENERO_FILME5
FOREIGN KEY(GENERO_FILME5) REFERENCES GENEROS(IDGENERO);