--3.1--
CREATE TABLE PAISES(
    IDPAIS INT,
    NOME_PAIS VARCHAR(1000),
    CONTINENTE VARCHAR(1000)
);

--3.2--
--CONSTRAINTS--

--PRIMARY KEY--
ALTER TABLE PAISES ADD CONSTRAINT PK_PAISES
PRIMARY KEY(IDPAIS);

ALTER TABLE PAISES MODIFY IDPAIS INT AUTO_INCREMENT;

--3.3--
--INSERTS--

--ÁFRICA--
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('África do Sul','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Angola','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Argélia','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Benin','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Botsuana','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Burkina Fasso','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Burundi','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Cabo Verde','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Camarões','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Chade','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Comores','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Congo','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Costa do Marfim','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Djibuti','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Egito','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Eritreia','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Etiópia','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Gabão','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Gâmbia','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Gana','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Guiné','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Guiné-Bissau','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Guiné-Equatorial','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Lesoto','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Libéria','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Líbia','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Madagáscar','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Malauí','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Mali','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Marrocos','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Maurício','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Mauritânia','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Moçambique','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Namíbia','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Níger','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Nigéria','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Quênia','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('República Centro-Africana','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('República Democrática do Congo','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Ruanda','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('São Tomé e Príncipe','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Senegal','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Serra Leoa','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Seicheles','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Tunísia','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Somália','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Suazilândia','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Sudão','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Sudão do Sul','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Uganda','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Tanzânia','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Togo','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Zâmbia','África');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Zimbábue','África');

--AMÉRICA--
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Antígua e Barbuda','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Argentina','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Bahamas','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Barbados','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Belize','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Bolívia','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Brasil','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Canadá','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Chile','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Colômbia','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Costa Rica','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Cuba','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Dominica','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('El Salvador','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Equador','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Estados Unidos','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Granada','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Guatemala','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Guiana','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Haiti','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Honduras','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Jamaica','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('México','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Nicarágua','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Panamá','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Paraguai','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Peru','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('República Dominicana','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Santa Lúcia','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('São Cristóvão e Névis','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('São Vicente e Granadinas','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Suriname','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Trinidad e Tobago','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Uruguai','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Venezuela','América');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Zimbábue','América');

--ÁSIA--
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Afeganistão','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Arábia Saudita','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Bangladesh','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Barein','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Brunei','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Butão','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Camboja','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Catar','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Cazaquistão','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('China','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Cingapura','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Coreia do Norte','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Coreia do Sul','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Emirados Árabes Unidos','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Filipinas','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Iêmen','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Índia','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Indonésia','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Irã','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Iraque','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Israel','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Japão','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Jordânia','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Kuwait','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Laos','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Líbano','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Malásia','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Maldivas','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Myanmar','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Mongólia','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Nepal','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Omã','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Paquistão','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Quirguistão','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Síria','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Sri Lanka','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Tadjiquistão','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Tailândia','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Timor-Leste','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Turquia','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Turcomenistão','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Uzbequistão','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Vietnã','Ásia');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Quirguistão','Ásia');

--EUROPA--
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Albânia','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Alemanha','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Andorra','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Armênia','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Áustria','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Azerbaijão','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Belarus','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Bélgica','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Bósnia-Herzegóvina','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Bulgária','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Chipre','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Croácia','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Dinamarca','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Eslováquia','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Eslovênia','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Espanha','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Estônia','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Finlândia','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('França','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Geórgia','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Grécia','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Hungria','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Irlanda','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Islândia','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Itália','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Letônia','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Liechtenstein','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Lituânia','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Luxemburgo','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Macedônia','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Malta','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Moldávia','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Mônaco','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Montenegro','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Noruega','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Países Baixos','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Polônia','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Portugal','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Reino Unido','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('República Tcheca','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Romênia','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Rússia','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('San Marino','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Sérvia','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Suécia','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Suíça','Europa');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Ucrânia','Europa');

--OCEANIA--
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Austrália','Oceania');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Fiji','Oceania');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Ilhas Marshall','Oceania');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Ilhas Salomão','Oceania');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Kiribati','Oceania');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Micronésia','Oceania');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Nauru','Oceania');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Nova Zelândia','Oceania');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Palau','Oceania');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Papua Nova Guiné','Oceania');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Samoa','Oceania');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Tonga','Oceania');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Tuvalu','Oceania');
INSERT INTO PAISES (NOME_PAIS, CONTINENTE) VALUES ('Vanuatu','Oceania');

