--10.1--
CREATE TABLE PLATAFORMAS(
    IDPLATAFORMA INT,
    NOME_PLATAFORMA VARCHAR(1000),
    LANCAMENTO_PLATAFORMA DATE
);

--10.2--
--CONSTRAINTS--

--PRIMARY KEY--
ALTER TABLE PLATAFORMAS ADD CONSTRAINT PK_PLATAFORMA
PRIMARY KEY(IDPLATAFORMA);

ALTER TABLE PLATAFORMAS MODIFY IDPLATAFORMA INT AUTO_INCREMENT;