--FILMES_MINHA_NOTA--
/*ESSE PROCEDURE SEPARA ALGUMAS INFORMAÇÕES DOS FILMES NO BANCO
SEPARADOS PELA NOTA QUE DEI AOS FILMES EM ORDEM DECRESCENTE*/

DELIMITER $

CREATE PROCEDURE filmes_minha_nota()
    BEGIN
        SELECT
            F.IDFILME AS "ID",
            F.NOME_FILME AS "Nome do Filme",
            DATE_FORMAT(F.DATA_LANCAMENTO,"%Y") AS "Lançamento",
            D.NOME_DIRETOR AS "Diretor",
            AA.NOME_ATOR AS "Atores",
            IFNULL(AB.NOME_ATOR, "****") AS "Atores",
            IFNULL(AC.NOME_ATOR, "****") AS "Atores",
            IFNULL(AD.NOME_ATOR, "****") AS "Atores",
            IFNULL(AE.NOME_ATOR, "****") AS "Atores",
            G.NOME_GENERO AS "Genero",
            F.CLASSIFICACAO_ETARIA AS "PG",
            F.DURACAO_FILME AS "Duração",
            F.MINHA_NOTA AS "Minha Nota"
        FROM FILMES F
        INNER JOIN DIRETORES D ON F.DIRETOR1 = D.IDDIRETOR
        LEFT JOIN ATORES AA ON F.ATOR1 = AA.IDATOR
        LEFT JOIN ATORES AB ON F.ATOR2 = AB.IDATOR
        LEFT JOIN ATORES AC ON F.ATOR3 = AC.IDATOR
        LEFT JOIN ATORES AD ON F.ATOR4 = AD.IDATOR
        LEFT JOIN ATORES AE ON F.ATOR5 = AE.IDATOR
        LEFT JOIN GENEROS G ON F.GENERO_FILME1 = G.IDGENERO
        ORDER BY MINHA_NOTA DESC;
    END
$

--ANIMES_MINHA_NOTA--
/*ESSE PROCEDURE SEPARA ALGUMAS INFORMAÇÕES DAS SERIES DE ANIMES SEPARADO PELA MINHA NOTA
EXCLUINDO OS FILMES DE ANIMES QUE ESTÃO NA MESMA CATEGORIA QUE TERÁ UMA PROCEDURE SEPARADA*/

DELIMITER $

CREATE PROCEDURE animes_minha_nota()
    BEGIN
        SELECT
            AN.IDANIME AS "ID",
            AN.NOME_ANIME AS "Nome do Anime",
            DATE_FORMAT(AN.DATA_LANCAMENTO, "%Y") AS "Lançamento",
            AE.NOME_ATUAL_ESTADO AS "Status",
            GA.NOME_GENERO AS "Gênero",
            GB.NOME_GENERO AS "Gênero",
            AN.QUANTIDADE_EPISODIOS AS "Número de Episódios",
            AN.MINHA_NOTA AS "Minha Nota"
        FROM ANIMES AN
        LEFT JOIN ATUAL_ESTADO AE ON AN.ATUAL_ESTADO = AE.IDATUAL_ESTADO
        LEFT JOIN GENEROS GA ON AN.GENERO_ANIME1 = GA.IDGENERO
        LEFT JOIN GENEROS GB ON AN.GENERO_ANIME2 = GB.IDGENERO
        WHERE AE.IDATUAL_ESTADO <> 7 AND AE.IDATUAL_ESTADO <> 8
        ORDER BY MINHA_NOTA DESC;
    END
$

--ANIMES_LONGA_MINHA_NOTA--
/*ESSE PROCEDURE SEPARA OS ANIMES LONGA-METRAGEM PELA MINHA NOTA DESC*/

DELIMITER $

CREATE PROCEDURE animes_longa_minha_nota()
    BEGIN
        SELECT
            AN.IDANIME AS "ID",
            AN.NOME_ANIME AS "Nome do Anime",
            DATE_FORMAT(AN.DATA_LANCAMENTO, "%Y") AS "Lançamento",
            AE.NOME_ATUAL_ESTADO AS "Status",
            GA.NOME_GENERO AS "Gênero",
            GB.NOME_GENERO AS "Gênero",
            AN.MINHA_NOTA AS "Minha Nota"
        FROM ANIMES AN
        LEFT JOIN ATUAL_ESTADO AE ON AN.ATUAL_ESTADO = AE.IDATUAL_ESTADO
        LEFT JOIN GENEROS GA ON AN.GENERO_ANIME1 = GA.IDGENERO
        LEFT JOIN GENEROS GB ON AN.GENERO_ANIME2 = GB.IDGENERO
        WHERE AE.IDATUAL_ESTADO = 7
        ORDER BY MINHA_NOTA DESC;
    END
$

--ANIMES_CURTA_MINHA_NOTA--
/*ESSE PROCEDURE SEPARA OS ANIMES CURTA METRAGEM COMO OVAS E AFINS PELA MINHA NOTA DESC*/

DELIMITER $

CREATE PROCEDURE animes_curta_minha_nota()
    BEGIN
        SELECT
            AN.IDANIME AS "ID",
            AN.NOME_ANIME AS "Nome do Anime",
            DATE_FORMAT(AN.DATA_LANCAMENTO, "%Y") AS "Lançamento",
            AE.NOME_ATUAL_ESTADO AS "Status",
            GA.NOME_GENERO AS "Gênero",
            GB.NOME_GENERO AS "Gênero",
            AN.MINHA_NOTA AS "Minha Nota"
        FROM ANIMES AN
        LEFT JOIN ATUAL_ESTADO AE ON AN.ATUAL_ESTADO = AE.IDATUAL_ESTADO
        LEFT JOIN GENEROS GA ON AN.GENERO_ANIME1 = GA.IDGENERO
        LEFT JOIN GENEROS GB ON AN.GENERO_ANIME2 = GB.IDGENERO
        WHERE AE.IDATUAL_ESTADO = 8
        ORDER BY MINHA_NOTA DESC;
    END
$