--11.1--
CREATE TABLE PRODUTORAS(
    IDPRODUTORA INT,
    NOME_PRODUTORA VARCHAR(1000),
    PAIS_PRODUTORA INT,
    FUNDADA DATE
);

--11.2--
--CONSTRAINTS--

--PRIMARY KEY--
ALTER TABLE PRODUTORAS ADD CONSTRAINT PK_PRODUTORAS
PRIMARY KEY(IDPRODUTORA);

ALTER TABLE PRODUTORAS MODIFY IDPRODUTORA INT AUTO_INCREMENT;

--PAIS--
ALTER TABLE PRODUTORAS ADD CONSTRAINT FK_PAIS_PRODUTORA
FOREIGN KEY(PAIS_PRODUTORA) REFERENCES PAISES(IDPAIS);